### ISSUE TITLE
Possible GWT problem: 'compile time user.agent value does not match runtime user.agent value'

### ISSUE THREAD

**Issue by bencomp** [europeana/REPOX#10]
After I compiled the whole system (on Mac OSX, JDK 8) and deployed the GUI in Tomcat 8 (in Docker, JRE 8), I get the following message the first time I visit the REPOX homepage:

```
ERROR: Possible problem with your *.gwt.xml module file.
The compile time user.agent value (safari) does not match the runtime user.agent value (gecko1_8). Expect more errors.
```

So far I haven't noticed anything that looks like a problem, but what does this mean? Can you only compile for one browser and must you deploy in the compilation environment?

**Comment by stzanakis** [comment]
Hello bencomp,

Thanks for your message! :)
Yes that is correct, the user.agent values have been reduced and some other values as well to reduce compilation time.
In your case, I guess you tried to access it through firefox(?), you need to update the file under `/repox-gui/src/main/java/harvesterUI/HarvesterUI.gwt.xml` and add the value `gecko1_8` like so:

`<set-property name="user.agent" value="safari, gecko1_8"></set-property>`

I believe that this should be enough. For more languages you have to enable them from the same file before building.
Just tested and this addon doesn't impact the speed anymore so I added the value in the file so you can just pull and build.

Hope this helps!

**Comment by bencomp** [comment]
Indeed I use Firefox. I'll take your word that this helps.

I have no development experience whatsoever when it comes to GWT, so I don't understand why such properties are there. (Similarly, I don't understand references to permutations at compile time or obfuscation in the pom.)

**Comment by stzanakis** [comment]
Don't worry, I don't have vast knowledge of gwt as well. :)
Let me know if everything deploys fine!

**Comment by bencomp** [comment]
Upon re-reading the README, I suddenly realise this is probably what was meant by 'permutations' in

> For development builds the permutations have been reduced in the file /repox-gui/src/main/java/harvesterUI/HarvesterUI.gwt.xml.
> For other configuration needs, this file needs to be reconfigured.

Do I understand that correctly?

**Comment by stzanakis** [comment]
That is correct!

**Comment by bencomp** [comment]
It would perhaps be nice if the documentation provided a link to the [GWT][1] documentation that explains the term, or explain the effect of the current (default) configuration to non-[GWT][2] developers. 

[1]: http://www.gwtproject.org/overview.html
[2]: http://en.wikipedia.org/wiki/Google_Web_Toolkit

The https://github.com/europeana/REPOX/commit/d051fb7f5ad31cf18079b9dd005c0c066b6b82e6 commit added support for Firefox in the default configuration, which solves my issue.
