### ISSUE TITLE
JVM option for runtime configuration file is named ambiguously

### ISSUE THREAD

**Issue by bencomp** [europeana/REPOX#12]
The README explains that providing `repox.data.dir=/path/to/config/dir` will make REPOX look for a `configuration.properties` file in that path. It's a minor issue and possibly I'm the only one bothered, but I think `repox.config.dir` is a clearer name for the JVM option. Inside the configuration.properties file, there are properties like `repository.dir` and `database.dir` that define paths for data. Not using `data` in a configuration file directory might save confusion :)

Providing an explicit example of how to start Tomcat with this option would be nice as well.

**Comment by stzanakis** [comment]
Yeah you are right!
It's cleaner like that, thanks for pointing that out, will update the code.

**Comment by stzanakis** [comment]
Hi there! I updated the code and the documentation with your suggestion. Now it will not "bother" you anymore! :D
Thanks for pointing this out, and suggestions are always welcome if you have any.
Please also close any issues that are resolved.

Thank you!
