### ISSUE TITLE
"Check [OAI-PMH URL]" only retrieves first page of sets

### ISSUE THREAD

**Issue by bencomp** [europeana/REPOX#13]
When I enter a URL for an OAI-PMH endpoint and click 'Check', REPOX retrieves the list of sets for me to choose from. Some PMH servers, however, return that list in pages. It appears that REPOX only retrieves the first page and does not allow me to retrieve more. Also, after clicking 'Check', the option to enter a setSpec manually is gone, because it is replaced by the dropdown list of retrieved sets.

I would like to have an option _retrieve more sets_, or perhaps _retrieve all sets_.

**Comment by stzanakis** [comment]
This is true, but it will be fixed in a future release so I will leave the issue open until then.

**Comment by stzanakis** [comment]
Fixed on development branch.
