### ISSUE TITLE
Folder Path option is overwritten while creating next Data Set

### ISSUE THREAD

**Issue by katjazin** [europeana/REPOX#16]
apache-tomcat-8.0.21
jdk1.8.0_45
mysql_5.5.39

Dear developers,
i have a follow problem. I have a dozen data sets under the same data provider. All the data is ingested out of file system ( per Folder ). While creating/updating the data sets folder path the same value is written in each already existing data set. 
There was no such problem with the version REPOX v2.2.6.
Please help!
Katja

PS: The problem doesn't seem to depend on tomcat/java- versions

**Comment by stzanakis** [comment]
Hi ktjazin,

There was a bug with the Folder strategy which has been just fixed.
It might be related to your problem.
Could you please update Repox to the latest commit from the development branch?

Simon

**Comment by katjazin** [comment]
It works quite good
Thanks a lot and sorry for the delay,
Katja

**Comment by stzanakis** [comment]
Great! Glad everything's fine! :)
