### ISSUE TITLE
Ingested records not showing up in GUI

### ISSUE THREAD

**Issue by roland-c** [europeana/REPOX#18]
Hi,
I cloned and compiled Repox today and tried to ingested a dataset. During the ingestion process the record count remained 0 in the GUI while the logging showed records were fetched and the record count in the database was accumulating. When I tried an export of these records no results showed up. Not sure what happened here but something is wrong with getting correct metadata results into the GUI. 
Any suggestions on how to get correct counts (AND records!) into Repox GUI would be greatly appreciated!

Thanks,
Roland

**Comment by stzanakis** [comment]
Hello,
Which protocol are you using to harvest?

**Comment by roland-c** [comment]
OAI-PMH.
In the meantime I let the process run but it didn't stop after harvesting all available records. The counter for records in the GUI is still 0, while in the database all records are available from the harvested source.

**Comment by stzanakis** [comment]
It's a little difficult to help you out.
You can send me the dataset details(to my email) and I can test it locally if you want

**Comment by roland-c** [comment]
Thanks Simon, but I think i just found what my problem is; the dataset I try to harvest is from a public OAI-PMH server that requires an API key. I wasn't aware of this fact since previously I got data from this service without this API key. The behaviour of this endpoint is obfuscated and I blame this issue now on the service side instead of the Repox side.

**Comment by stzanakis** [comment]
I'm glad you find that out.
Please close the ticket if it cleared out.
Thanks!
