### ISSUE TITLE
OAIHandler ListRecords for all records loops after first page/resumption token

### ISSUE THREAD

**Issue by CanOfBees** [europeana/REPOX#19]
We're experiencing some strange behavior from a fresh build of the 3.0.0 development branch. If we query repox with a set=... parameter, resumption tokens work as expected. If we query repox without a set=... parameter, i.e. query for all records, then the resumption token returns the first page of records.

I don't recall modifying any associated code for this, but is there somewhere I can look to modify this behavior?

Thanks!

EDIT: using the ListIdentifier verb against the entire application exhibits the same behavior.

**Comment by stzanakis** [comment]
First of all please get the latest version from the development branch, version 3.0.0 seems to have still some important bugs.
I checked what you are referring to and this is not implemented in Repox. You can retrieve all records from a specific set not all records from all sets.

If you want to modify this behavior the code is under the repox-server-oai module.
Another way of doing what you want is programmatically ListSets and then retrieve each one of them.

**Comment by markpbaggett** [comment]
Stzanakis,

Sorry, am I reading this wrong or are you saying that it shouldn't be possible to harvest a full feed from Repox without specifying a set.  For instance, our Repox OAI endpoint is here: http://dpla.lib.utk.edu/repox/OAIHandler

Should you not be able to use http://dpla.lib.utk.edu/repox/OAIHandler?verb=ListRecords&metadataPrefix=MODS

Just making sure I'm not misreading this.

**Comment by stzanakis** [comment]
Hi mark,

I am not saying it shouldn't be possible. 
It should be possible to retrieve all records when the "set" parameter is not used, as it is specified in the <a href="http://www.openarchives.org/OAI/openarchivesprotocol.html">OAI-PMH</a> protocol specification itself.

I am saying that the implementation that repox is using doesn't support this behavior currently.

**Comment by no-reply** [comment]
@stzanakis can you clarify. I harvest a lot of Repox instances without using a `set` parameter. This is the first problem I have had with any of those harvests.

**Comment by stzanakis** [comment]
If you harvest from a current version of a Repox instance without a "set" parameter, the response is not guaranteed and will not return the list of all items with the specified "metadataPrefix".
The specific implementation that the current Repox has doesn't support getting all records when the "set" parameter is not used.
I hope this is more clear.

**Comment by stzanakis** [comment]
The issue has been fixed. It is possible to ingest without a "set" and duplicated incoming records will be overwritten. Improved record counts as well. On development branch for now.
Any found issues please report.
