### ISSUE TITLE
Install error: Missing artifact javax.transaction:jta:jar:1.0.1B

### ISSUE THREAD

**Issue by dhenry314** [europeana/REPOX#20]
I encountered the following error after running 'mvn clean install' the first time:

'Missing artifact javax.transaction:jta:jar:1.0.1B'

I was able to complete the build by manually downloading and installing the jar file in the Maven repository.

**Comment by stzanakis** [comment]
Yes! 
That's true and has been already fixed in the development branch.
Thanks for the report though.
