### ISSUE TITLE
Problems by update from 2.2.6

### ISSUE THREAD

**Issue by katjazin** [europeana/REPOX#21]
Dear Simon,
i build and installed the current development version of Repox as discribed. 
As i tried to ingest the data per folder i got following problems:
1. ID-Extraction fails (data & configuration as for v. 2.2.6)
2. When i try to re-ingest the data ("ingest now"), there is no reaction neither in logs nor in "running tasks". I have to restart tomcat to start the ingest. 
3. When I succeeded to start the ingest i got memory leak
Best regards
Katja

**Comment by stzanakis** [comment]
Hello Katha,

Are the permissions on the file system of the repox directory correct?
Since you do not have any logs, would it be possible to send me privately a sample of the data that you are trying to ingest so I can test them locally?

Simon

**Comment by stzanakis** [comment]
This issue is invalid since there was a misconfiguration on the specific instance, as discussed and solved though private emails.
