### ISSUE TITLE
Auto-import XSL stylesheets and OAI sets

### ISSUE THREAD

**Issue by CanOfBees** [europeana/REPOX#30]
Hi @stzanakis - 

The title is a little rough, but I'm attempting to put together a vagrant-based testing environment for REPOX. I want to give the testing environment to co-workers and colleagues with several "preconfigured" stylesheets, OAI sets, and metadata schema. 

As best I can tell, aside from the actual <record>s, none of the stylesheets and schema are store in the MySQL database. 

If you have time, could you provide some guidance for adding these programmatically? I've looked around in the [harvesterUI code](https://github.com/europeana/REPOX/blob/master/gui/src/main/java/harvesterUI/server/xmapper/XMApperServicesServer.java), but I know very little about java. It looks like there are some checks for directories, but is there already some checks for pre-existing stylesheets, etc?

Thank you in advance for any insights you're able to share.
Best!

**Comment by stzanakis** [comment]
Hi @CanOfBees 

Yes it should be possible from the rest api that repox has, it's under the context /mappings.
Check the following https://github.com/europeana/REPOX/blob/master/server/rest-jersey/src/main/java/org/theeuropeanlibrary/repox/rest/servlets/MappingResource.java

But you'll need to properly construct the request, and I do not have an example at hand.

In general, you can have a look at the swagger interface of what you can use, it's under the context /repox/gui/index.html
Swagger might not display properly what you need to add in the body, so you might need to look a bit the code..

Hope that helps!

**Comment by markpbaggett** [comment]
Simon,

Sincere thanks.  This is exactly what we needed.   I have a terribly dumb question though.  For some reason, both the Swagger UI and curling consistently give us a 401 response when we query with our authentication information. We assume that we don't have authorization and authentication configured properly in Swagger (but that may be way off).  

Any ideas where we could look for what could be causing this? Or, do you have any ideas about what we could be doing wrong.

Thanks in advance for any insights.

**Comment by stzanakis** [comment]
Sorry for the late reply, I was away.

So if you read the repox wiki about swagger, https://github.com/europeana/REPOX/wiki/Using-Swagger-UI you can find where the credentials are configured for the rest-apis, which are different from the GUI accounts.

**Comment by CanOfBees** [comment]
@stzanakis thank you! The help is greatly appreciated.

**Comment by markpbaggett** [comment]
@stzanakis, yes!  Thank you.  I should have looked at the wiki -- I did not. 

Thanks again.  I think we have what we need to do this now, and I think we can close this issue.

**Comment by CanOfBees** [comment]
@stzanakis @markpbaggett closing. 

Cheers!
