### ISSUE TITLE
Local installation does not start - FileNotFoundException

### ISSUE THREAD

**Issue by neumannm** [europeana/REPOX#31]
I'm new to repox and wanted to try it out on my local machine. I'm not an expert with tomcat and databases but I think I got everything configured as explained in the instructions - I have set up a new database and a new user 'repox' with all privileges. I have installed tomcat and I have also created a directory 'repoxData' that user tomcat8 owns. I have adjusted the configuration settings and building the .war worked fine so far.

When I place the .war in the webapps folder, start tomcat and open localhost:8080/repox, I receive an error "Error: session could not be loaded.". Following suggestions from a closed issue from last year about the same message, I checked catalina.out and repox.log. Here's what I found:

catalina.out:
```
java.lang.NullPointerException
at harvesterUI.server.RepoxServiceImpl.getInitialConfigData(RepoxServiceImpl.java:127)
``` 

repox.log:
```
FATAL pt.utl.ist.configuration.DefaultRepoxContextUtil:55 [http-nio-8080-exec-2] - Unable to load DefaultRepoxManager
java.io.FileNotFoundException: /media/<username>/data/Development/repoxData/configuration/countries.txt (Permission denied)
```

The database is still empty and also the repoxData directory is empty. 

I think the problem must be something simple but I'm not able to figure out what could be the reason.

**Comment by stzanakis** [comment]
Is that `<username>` in the path something you changed manually? Otherwise this could be the problem in your configuration.

If not I can say the following:
Ok as the error describes there is a permission problem.
Are you sure that the user running tomcat is tomcat8?
You can check that if you run `ps aux | grep tomcat`.

Once you are sure of the user you can run on the repoxData directory, if for example it's tomcat8 the user.
`chown -R tomcat8:tomcat8 /media/<username>/data/Development/repoxData`
Also just to rule out the permission problem you can run `chmod -R 777 /media/<username>/data/Development/repoxData`

Then you can restart tomcat and see if that worked out.

**Comment by neumannm** [comment]
Yes, there is actually my user name instead of <username> in the path, I just didn't want to expose it.

I did everything as you suggested. I checked that tomcat8 is indeed the user running tomcat. I also ran `chown` as you showed to also set the group to tomcat8. After the error persisted, I also used `chmod` command. Unfortunately all this didn't work out, I still get this error when I restart tomcat and open the application. Any other ideas?

**Comment by stzanakis** [comment]
Ok next test:
Go on the webapps directory of tomcat and run:
`find . -type f -name "countries.txt"`

If it doesn't give you a location of the countries.txt file, then stop tomcat.
Copy this file:
https://github.com/europeana/REPOX/blob/master/manager/src/main/resources/countries.txt

Into the `webapps/repox/WEB-INF/classes/` update the path if yours is a bit different of course.
Restart tomcat.

**Comment by neumannm** [comment]
There is indeed no countries.txt under webapps. 
I did as you said but it didn't help. I also don't understand how it should work - the error message is looking for this file under `/media/...` in this repoxData directory I created, so how should placing it in the `WEB-INF/classes/` folder help? Should I also change the path in the `configuration.properties` there?

**Comment by stzanakis** [comment]
Well what happens is it checks if the file `countries.properties` file is in the location of the configuration directory already, if not it will generate if from the project.
The thing is I tried to install it from scratch and I couldn't reproduce the problem you are facing.
You haven't updated the `configuration.properties` file? If you haven't, yes you need to update the configuration.properties file as well.

**Comment by neumannm** [comment]
I see, thanks for the explanation. 

Ok so back to the configuration.properties file. As far as I understood the instructions, I edited this file at the location `.../git/REPOX/resources/src/main/resources/` and I adjusted all the example directory paths to begin with `/media/<username>/data/Development/repoxData/`, a directory I created beforehand. This directory is empty. The paths point to sub-directories in there and I assumed that the application will create those sub-directories once it is running. Of course I also adjusted the email settings and the database settings to fit to my MySQL settings.
After I made the changes in the file, I built the .war file with `mvn clean install -Pproduction` command. I copied the .war file to tomcat webapps folder. 

So now tomcat creates a folder `repox` inside its `webapps` folder where we find again the configuration file under `WEB-INF/classes/`. My question was, do I have to edit this file now manually again because this `countries.txt` is now also in this folder and not in any of the directories that are specified in the configuration file?

**Comment by stzanakis** [comment]
Ah ok that's what you meant. Then you have done the steps correctly.
You could create the configuration directory under the repoxData directory and copy the countries.txt file to that directory and retry.
But in general I find it weird it doesn't work from scratch, I cannot reproduce it myself.
Did you pull from the develop branch? What is the environment you have tomcat running?
Are there any other relevant logs produced?

P.S. I would recommend using postgres, we use postgres so it could potentially be more up to date..

**Comment by neumannm** [comment]
It's so weird, even after copying countries.txt manually to repoxData/configuration/ and making it accessible for everyone, I still get this "FileNotFoundException (Permission denied)" error. Maybe I should start all over again although I have no idea what could have gone wrong because the few steps for installation are actually so simple.

Yes I pulled repox from development branch. (Actually it wouldn't even make a difference I think because according to git, development is even with master.)

I am running Apache Tomcat/8.0.32 (Ubuntu) on Ubuntu 16.04.2 LTS 64bit version. Java version is 1.8.0_121. MySQL version Ver 15.1 Distrib 10.0.29-MariaDB.

Concerning postgres, actually that was the first thing I tried because I wanted to follow the instructions as closely as possible. I followed all the relevant steps in the install script that is shipped with repox (I did not just run it because I already had Java installed and also wanted to use different paths for git and repoxData directories). But when repox didn't start, I tried again with mysql because I had that already installed and I'm a little bit more familiar with it. 
But again, I think I will have to try again from scratch, and I will try postgres again in the process. Although for me it doesn't look like a database problem.

And yes I just noticed another thing in catalina.out that happens when starting tomcat and when it deploys the war:

```
INFORMATION: Deploying web application archive /var/lib/tomcat8/webapps/repox.war
Apr 20, 2017 9:01:21 AM org.apache.jasper.servlet.TldScanner scanJars
INFORMATION: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
java.lang.NullPointerException
	at org.oclc.oai.util.OAIUtil.getTag(OAIUtil.java:233)
	at org.oclc.oai.server.catalog.XMLRecordFactory.<init>(XMLRecordFactory.java:25)
...
```

**Comment by neumannm** [comment]
Ok so... I got it to work. After uninstalling and deleting everything from my first attempts, I again followed the install script, but this time more closely. That is, I did *not* change the directory paths in there. I put repoxData under `/data/repoxData/` and the source under `/data/git/`. I think this is the only difference in the whole procedure.

I even tried both database systems, so both postgres and mysql, so be sure that the problem wasn't there. And it wasn't, it also runs with mysql as database.

So I'm clueless as to why it didn't work out in the first attempt. To me it looks like it had to do with me using another path on my file system for repoxData directory. But that doesn't make so much sense, does it? Is this some bug or maybe a feature? I think I will play around further, putting the directory in several different places and try to find out what's going on there.

**Comment by stzanakis** [comment]
You have done the steps correctly so it was strange to me that it wasn't working.
I'm glad it worked out at the end. Could be the build that was corrupted..

About the directory paths, no normally it should work anywhere, the `/data/repoxData/` is just an example.
In fact you don't even need to create the `repoxData` directory beforehand, as long as you have it in the configuration, like here `/data/repoxData` it will be created under `/data` directory as long as the permissions are correct and all subdirectories under it.
Or maybe the `<username>` had characters in it that were not properly resolved from the application?
In any case if you find something else relevant plz comment it here and close the issue:)

**Comment by neumannm** [comment]
I did not find any reason why it didn't work with another directory path. Maybe indeed some permission issue I'm not aware of.
