### ISSUE TITLE
Defining XSD and Schema Version with Swagger APIs?

### ISSUE THREAD

**Issue by markpbaggett** [europeana/REPOX#32]
Hello,

Is there a public API that can be used to  define a schema definition and version?  If you add a dataset to a provider with a schema definition and run a harvest, the harvest will work but you get a "this metadata format is not supported by the item or by the repository." If you define the schema / version in the GUI, the OAI request will work, but I'm wondering if there is an API you can use so these definitions can be scripted?

Let me know if I can provide anything to help answer this.

Best,
Mark

**Comment by stzanakis** [comment]
No this was not implemented as a REST call.
What you could do is modify/create the file repoxData/configuration/metadataSchemas.xml 

For example:
`<?xml version="1.0" encoding="UTF-8"?>

<metadataSchemas>
  <metadataSchema>
    <shortDesignation>oai_dc</shortDesignation>
    <namespace>http://www.openarchives.org/OAI/2.0/</namespace>
    <bOAIAvailable>true</bOAIAvailable>
    <versions>
      <version number="2.0" xsdLink="http://www.openarchives.org/OAI/2.0/oai_dc.xsd"/>
    </versions>
  </metadataSchema>
</metadataSchemas>
`

Check the format there and add new elements. Requires restart if the application is running..

**Comment by markpbaggett** [comment]
@stzanakis, thanks! This will work Thanks again for your help.  Closing.
