### ISSUE TITLE
How to programmatically excluding records

### ISSUE THREAD

**Issue by CanOfBees** [europeana/REPOX#33]
Hi Simon -- 

I'm curious if there's a way to programmatically exclude records that match a certain criteria. For example, I would like to exclude every record in a set that doesn't match the following XPath; e.g.
```xml
<xsl:template match="/oai_dc:dc/dc:description[contains(., "Thinks bees are pretty great.")]">
  <!-- do some processing -->
</xsl:template>
```
currently, using this sort of approach in our repox stylesheets results in OAI-PMH responses that look like this:
```xml
<record>
  <header>
    <identifier>an.identifier</identifier>
    <datestamp>2015-07-11</datestamp>
   <setSpec>a_test_set</setSpec>
  </header>
  <metadata> </metadata>
</record>
```
It looks like the response uses a hardcoded `<metadata>` element, with the output of the XSLT serialized inside that element. Is there a way around this?

I'm not sure I phrased this question very clearly, but all the same: thank you for your time and help!

Best!

**Comment by stzanakis** [comment]
Hello,

No there is no way as you describe it.
The feature you are using is to convert the actual record to something else before representing it, as you identified. Of course you could create another dataset with only the records you want, and then use that. Don't know if this could be something viable for you though.
The other option is to mark records as deleted from the api and you need to know which id's to delete before hand, but it's not probably what you want..

Hope that helps..

Simon

**Comment by CanOfBees** [comment]
Hi Simon - 
thanks for your feedback. We came up with a work-around for this so I'll close this ticket.

Best,
Bridger
