### ISSUE TITLE
Updating Saxon Version

### ISSUE THREAD

**Issue by CanOfBees** [europeana/REPOX#35]
Hi Simon -- 
Apologies for what's probably a really basic question, but if I wanted to build Repox with a newer version of Saxon, would it just be the case of updating the top-level Maven configuration file; i.e. REPOX/pom.xml?

Looking through the source I don't see other places that would need modification but I thought I might be missing something.

Thank you for your help.
Best,
Bridger

**Comment by stzanakis** [comment]
Hi there,

Yes you can just change the property variables there. This should normally be sufficient..
But of course the versions could be incompatible with the current code, so just try and see what happens.

Simon

**Comment by CanOfBees** [comment]
That sounds great. Thanks for the response.

Bridger
