### ISSUE TITLE
Using post mappings API to create a new XSL file through HTTP post.

### ISSUE THREAD

**Issue by markpbaggett** [europeana/REPOX#40]
Hello Simon,

A couple of weeks ago I got inspired to write a [Python client to the Repox API](https://github.com/markpbaggett/pyrepox). I have a few issues that I'm still working through, but the biggest one is with the [Create a new mapping - XSL file through HTTP POST API](https://github.com/europeana/REPOX/blob/7649f681448d2fbf0f2c0211ee6a7230a4fdc47f/client/client-rest-jersey/src/main/java/eu/europeana/repox/rest/client/accessors/MappingsAccessor.java#L138). The Swagger interface suggests I need to pass an object that looks something like this:

`{
  "bodyParts": [
    {
      "entity": "Object",
      "headers": "javax.ws.rs.core.MultivaluedMap<java.lang.String, java.lang.String>",
      "mediaType": {
        "type": "",
        "subtype": "",
        "parameters": "Map[string,string]",
        "wildcardType": false,
        "wildcardSubtype": false
      },
      "parent": "MultiPart",
      "providers": "Providers",
      "contentDisposition": {
        "type": "",
        "parameters": "Map[string,string]",
        "fileName": "",
        "creationDate": "",
        "modificationDate": "",
        "readDate": "",
        "size": 0
      },
      "parameterizedHeaders": "javax.ws.rs.core.MultivaluedMap<java.lang.String, org.glassfish.jersey.message.internal.ParameterizedHeader>",
      "messageBodyWorkers": "MessageBodyWorkers"
    }
  ],
  "entity": "Object",
  "contentDisposition": {
    "type": "",
    "parameters": "Map[string,string]",
    "fileName": "",
    "creationDate": "",
    "modificationDate": "",
    "readDate": "",
    "size": 0
  },
  "parameterizedHeaders": "javax.ws.rs.core.MultivaluedMap<java.lang.String, org.glassfish.jersey.message.internal.ParameterizedHeader>",
  "providers": "Providers",
  "headers": "javax.ws.rs.core.MultivaluedMap<java.lang.String, java.lang.String>",
  "mediaType": {
    "type": "",
    "subtype": "",
    "parameters": "Map[string,string]",
    "wildcardType": false,
    "wildcardSubtype": false
  },
  "parent": "MultiPart",
  "messageBodyWorkers": "MessageBodyWorkers"
}`

I don't think this is quite right, and I thought I'd ask if you had an example of how I could curl against this or what the REST interface is actually looking for before I try anything else.

Thanks in advance for any guidance you can provide.

Happy New Year, :fireworks: :champagne: :fireworks: 
Mark

**Comment by markpbaggett** [comment]
Simon,

Apologies. I just noticed the comment here that posts for the mappings API from Swagger are not allowed:

https://github.com/europeana/REPOX/blob/7649f681448d2fbf0f2c0211ee6a7230a4fdc47f/gui/src/main/webapp/examples/MappingsModelExamples.txt#L1

Not sure how I missed that. 

Best,
Mark

**Comment by stzanakis** [comment]
Hi Mark,

Sorry for the late reply, but I was away the last weeks.
So the link you've sent is the java client. The endpoint of the server code for creating a mapping is here [link](https://github.com/europeana/REPOX/blob/7649f681448d2fbf0f2c0211ee6a7230a4fdc47f/server/rest-jersey/src/main/java/org/theeuropeanlibrary/repox/rest/servlets/MappingResource.java#L148)

Unfortunately I do not have an example of what you are looking for and we also do not provide support/development on repox anymore(I try to help as much as I can unofficially sometimes though, providing it won't take too much time..)

So if the java client wasn't enough to figure out the python part, maybe it would be better to try the java server endpoint for creating the mapping, provided above.

I hope that helps somehow.

Simon

**Comment by markpbaggett** [comment]
@stzanakis, thanks for your help.
