### ISSUE TITLE
mvn clean install -Pproduction failes at marc4j-2.6.3

### ISSUE THREAD

**Issue by spamhareem** [europeana/REPOX#44]
It seems that artifactory.eanadev.org is not allowing the dependancy marc4j-2.6.3 to be downloaded. Please see error below.

[ERROR] Failed to execute goal on project repox-commons: Could not resolve dependencies for project repox:repox-commons:jar:3.2.1-SNAPSHOT: Failed to collect dependencies at marc4j:marc4j:jar:2.6.3: Failed to read artifact descriptor for marc4j:marc4j:jar:2.6.3: Could not transfer artifact marc4j:marc4j:pom:2.6.3 from/to artifactory.eanadev.org (http://artifactory.eanadev.org/artifactory/ext-release-local): Access denied to: http://artifactory.eanadev.org/artifactory/ext-release-local/marc4j/marc4j/2.6.3/marc4j-2.6.3.pom , ReasonPhrase:Forbidden.

**Comment by stzanakis** [comment]
Hi there!
We have updated the access, should be fine now.
Could you try again, and let me know if it works?

**Comment by spamhareem** [comment]
Thank you for the quick action. The issue has now been fixed and I was able to continue with the installation.
