### ISSUE TITLE
PostgreSQL database server - PostgreSQL v12 are tested versions?

### ISSUE THREAD

**Issue by tiradoma** [europeana/REPOX#46]
Hi, we're trying to create a REPOX database and we only work with PostgreSQL v12.

Please, may you tell me if REPOX can work with PostgreSQL v12?

Thanks in advance!

**Comment by stzanakis** [comment]
Hi @tiradoma,

This project is not maintained anymore.
Postgres was working up to version 9(you can see in the README).
Perhaps it's working for version 12 as well but it hasn't been tested.

Cheers!

**Comment by tiradoma** [comment]
Thanks a lot for your answer, anyway!
