### ISSUE TITLE
Enable more verbose logging?

### ISSUE THREAD

**Issue by CanOfBees** [europeana/REPOX#6]
Hi all, 

Apologies for this question, but I haven't been able to make any headway with this yet. I'd like to enable DEBUG-level logging, but my attempts at modifying the REPOX/manager/src/main/resources/log4j.properties file haven't been successful. If you haven't guessed by now, I'm not very familiar with Java applications like REPOX. Should I be trying to modify the log4j.properties file, or is this something that should be added to the REPOX/resources/src/main/resources/configuration.properties (or somewhere else entirely)?

Thank you, as always, for your time and trouble.

**Comment by stzanakis** [comment]
Unfortunately the log4j logging is not configured correctly so the only way to get logging information is from the log files of tomcat e.g catalina.out and from the files that repox generates, for example when ingesting.

**Comment by stzanakis** [comment]
Hello Bridger,

I have fixed the log4j configuration and is now included in the `repox-resources` module.
You can make you modifications there and then build repox, as you can see it will generate a logRepox.log file in your tomcat logs directory.

Cheers!

**Comment by CanOfBees** [comment]
Hi Simon, 

That's fantastic, thank you! I'll be testing this in the next few days.
