### ISSUE TITLE
OAI-PMH Server  error

### ISSUE THREAD

**Issue by neshelman** [europeana/REPOX#7]
Hi Simon, 

I get this error when I try to run the OAI-PMH Server:

HTTP Status 404 - /repox-server-oai-2.6.0-SNAPSHOT/
type Status report
message /repox-server-oai-2.6.0-SNAPSHOT/
description The requested resource is not available.
Apache Tomcat/6.0.43

I don't see anything of use in the log files. Any ideas? Do I need the server if we just want to harvest OAI? Thanks --Nicholas

**Comment by stzanakis** [comment]
Hi there!

First of all there is a lot of explanation in the README. https://github.com/europeana/REPOX/blob/master/README.md

And yes you can deploy the OAI-PMH as standalone. It is specified in the README.
You need to run:
`process-resources -Pcopy-resources`    

(It copies the needed resources from the resources module, so you can deploy as standalone)

Refresh the project(if in IDE)
`clean package`

Also you need to add the context /OAIHandler to access it

eg.
/repox-server-oai-2.6.0-SNAPSHOT/OAIHandler
