### ISSUE TITLE
License used?

### ISSUE THREAD

**Issue by dltj** [europeana/REPOX#8]
There doesn't seem to be a LICENSE file in the source code which indicates the open source license.  Can this be added, please?

**Comment by stzanakis** [comment]
Yes we will add it soon, we had some internal issues about the license that will be used.

**Comment by stzanakis** [comment]
License has been added.

**Comment by dltj** [comment]
Thank you -- I've updated the entry for Repox on FOSS4Lib: https://foss4lib.org/package/repox

**Comment by stzanakis** [comment]
That's great!
Thanks!
